import { DEFAULT_LANG, type LangCode } from './languages';

/**
 * i18n layer for STATIC UI text only — commands, buttons, section labels,
 * errors, and the disclaimer. These are fixed and finite, so they live here as
 * plain strings: zero token cost, instant, and reviewable (important for the
 * medical disclaimer, which must read correctly in every language).
 *
 * The DYNAMIC medicine content (uses, side effects, warnings) is NOT here — it
 * is generated by the LLM directly in the user's language (see awareness.prompt).
 *
 * To add a language: add a Strings block keyed by its LangCode. Done.
 */

type WarningKey = 'pregnancy' | 'liver' | 'kidney' | 'alcohol' | 'children' | 'elderly';

export interface Strings {
  disclaimer: string;
  welcome: string;
  help: string;
  usage: (used: number, limit: number, remaining: number) => string;
  rateLimit: (hours: number, limit: number) => string;
  lowConfidence: (reason: string | null) => string;
  notAMedicine: string;
  sendPhoto: string;
  sendImage: string;
  downloadFailed: string;
  extractionFailed: string;
  imageTooLarge: (mb: string) => string;
  somethingWrong: string;
  purposeQuestion: (name: string, ingredients: string) => string;
  purposeTypePrompt: string;
  purposeLabels: Record<string, string>;
  typeLabel: string;
  skipLabel: string;
  analysis: {
    contains: string;
    drugClass: string;
    howItWorks: string;
    commonUses: string;
    commonSideEffects: string;
    seriousSideEffects: string;
    warnings: string;
    warningKeys: Record<WarningKey, string>;
    interactions: string;
    overdoseAwareness: string;
    fdaVerified: string;
  };
}

/**
 * Shown on /start and /language BEFORE we know the user's language, so it is
 * intentionally bilingual. The picker buttons themselves are the language names
 * in their own script, so the choice is unambiguous.
 */
export const LANGUAGE_PROMPT =
  '🌐 *Please choose your language*\n' +
  'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ';

function escapeMd(text: string): string {
  return text.replace(/([*_`\[\]])/g, '\\$1');
}

/* --------------------------------- English --------------------------------- */

const EN_DISCLAIMER =
  '⚠️ This is educational information only and not medical advice. Always consult a qualified doctor before taking, changing, or stopping any medicine.';

const en: Strings = {
  disclaimer: EN_DISCLAIMER,
  welcome:
    `👋 *Welcome to Dawa Saathi — your medicine awareness companion*\n\n` +
    `Send me a photo of any medicine label and I'll explain in simple language:\n` +
    `  • What it's commonly used for\n` +
    `  • Common and serious side effects\n` +
    `  • Important warnings\n\n` +
    `You can scan up to 3 medicines per day for free.\n\n` +
    EN_DISCLAIMER,
  help:
    `*How to use Dawa Saathi:*\n\n` +
    `1. Take a clear, well-lit photo of the medicine label\n` +
    `2. Send the photo to this chat\n` +
    `3. Wait a few seconds for the analysis\n\n` +
    `*Tips for best results:*\n` +
    `  • Focus on the name and ingredients\n` +
    `  • Avoid glare and shadows\n` +
    `  • Hold steady and close\n\n` +
    `*Commands:*\n` +
    `  /start — Welcome message\n` +
    `  /language — Change language\n` +
    `  /help — Show this help\n` +
    `  /usage — Check today's remaining scans\n\n` +
    EN_DISCLAIMER,
  usage: (used, limit, remaining) =>
    `📊 *Today's usage:* ${used} of ${limit} scans used\n` +
    `Remaining: *${remaining}*\n\n` +
    EN_DISCLAIMER,
  rateLimit: (hours, limit) =>
    `🛑 *Daily limit reached*\n\n` +
    `You've used your ${limit} free scans for today. ` +
    `Your limit resets in about ${hours} hour${hours === 1 ? '' : 's'}.\n\n` +
    EN_DISCLAIMER,
  lowConfidence: (reason) =>
    `🔍 *I couldn't read this clearly enough to be sure*\n\n` +
    (reason ? `_${escapeMd(reason)}_\n\n` : '') +
    `For your safety, I won't guess the medicine name — a wrong guess could be dangerous.\n\n` +
    `Please send a clearer photo:\n` +
    `  • Good lighting, no glare\n` +
    `  • Focus on the medicine name and ingredients\n` +
    `  • Hold the camera steady and close\n\n` +
    `_This attempt was NOT counted against your daily limit._\n\n` +
    EN_DISCLAIMER,
  notAMedicine:
    `🤔 *That doesn't look like a medicine package*\n\n` +
    `Please send a clear photo of a medicine strip, bottle, or box.\n\n` +
    `_This attempt was NOT counted against your daily limit._\n\n` +
    EN_DISCLAIMER,
  sendPhoto:
    `Please send a *photo* of your medicine label.\n\n` +
    `Use /help for instructions.\n\n` +
    EN_DISCLAIMER,
  sendImage: `Please send an *image* of your medicine label.\n\n` + EN_DISCLAIMER,
  downloadFailed:
    `❌ Couldn't download the image. Please try sending it again.\n\n` + EN_DISCLAIMER,
  extractionFailed:
    `❌ Couldn't read the image. Please try a clearer photo.\n\n` + EN_DISCLAIMER,
  imageTooLarge: (mb) =>
    `📦 Image is too large. Please send an image under ${mb} MB.\n\n` + EN_DISCLAIMER,
  somethingWrong:
    `❌ Something went wrong preparing the information. Please send the photo again.\n\n` +
    EN_DISCLAIMER,
  purposeQuestion: (name, ingredients) =>
    `✅ I read: *${escapeMd(name)}*\n` +
    (ingredients ? `Ingredient: ${escapeMd(ingredients)}\n\n` : '\n') +
    `To give you the *right* information, what are you using this for?`,
  purposeTypePrompt: `Please type what you are using it for (e.g. "for skin marks", "for periods").`,
  purposeLabels: {
    skin: '🧴 Skin / pigmentation',
    bleeding: '🩸 Bleeding / periods',
    pain: '💢 Pain / fever',
    infection: '🦠 Infection',
    bp: '❤️ BP / heart',
    sugar: '🩺 Diabetes / sugar',
    acidity: '🔥 Acidity / stomach',
    allergy: '🤧 Allergy / cold',
  },
  typeLabel: '✍️ Type my reason',
  skipLabel: '⏭️ Skip',
  analysis: {
    contains: 'Contains',
    drugClass: 'What kind of medicine',
    howItWorks: 'How it works',
    commonUses: 'Commonly used for',
    commonSideEffects: 'Common side effects',
    seriousSideEffects: '🚑 See a doctor immediately if',
    warnings: '⚠️ Warnings',
    warningKeys: {
      pregnancy: 'Pregnancy',
      liver: 'Liver',
      kidney: 'Kidney',
      alcohol: 'Alcohol',
      children: 'Children',
      elderly: 'Elderly',
    },
    interactions: 'Be careful with',
    overdoseAwareness: '🚨 Overdose awareness',
    fdaVerified: '✓ Ingredient verified against FDA drug database.',
  },
};

/* --------------------------------- Kannada --------------------------------- */

const KN_DISCLAIMER =
  '⚠️ ಇದು ಕೇವಲ ಶೈಕ್ಷಣಿಕ ಮಾಹಿತಿಯಾಗಿದೆ, ವೈದ್ಯಕೀಯ ಸಲಹೆಯಲ್ಲ. ಯಾವುದೇ ಔಷಧಿಯನ್ನು ತೆಗೆದುಕೊಳ್ಳುವ, ಬದಲಾಯಿಸುವ ಅಥವಾ ನಿಲ್ಲಿಸುವ ಮೊದಲು ಯಾವಾಗಲೂ ಅರ್ಹ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.';

const kn: Strings = {
  disclaimer: KN_DISCLAIMER,
  welcome:
    `👋 *ದವಾ ಸಾಥಿಗೆ ಸ್ವಾಗತ — ನಿಮ್ಮ ಔಷಧಿ ಅರಿವಿನ ಸಂಗಾತಿ*\n\n` +
    `ಯಾವುದೇ ಔಷಧಿಯ ಲೇಬಲ್‌ನ ಫೋಟೋ ಕಳುಹಿಸಿ, ನಾನು ಸರಳ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸುತ್ತೇನೆ:\n` +
    `  • ಇದನ್ನು ಸಾಮಾನ್ಯವಾಗಿ ಯಾವುದಕ್ಕೆ ಬಳಸುತ್ತಾರೆ\n` +
    `  • ಸಾಮಾನ್ಯ ಮತ್ತು ಗಂಭೀರ ಅಡ್ಡ ಪರಿಣಾಮಗಳು\n` +
    `  • ಮುಖ್ಯ ಎಚ್ಚರಿಕೆಗಳು\n\n` +
    `ಪ್ರತಿದಿನ 3 ಔಷಧಿಗಳನ್ನು ಉಚಿತವಾಗಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಬಹುದು.\n\n` +
    KN_DISCLAIMER,
  help:
    `*ದವಾ ಸಾಥಿ ಬಳಸುವುದು ಹೇಗೆ:*\n\n` +
    `1. ಔಷಧಿಯ ಲೇಬಲ್‌ನ ಸ್ಪಷ್ಟವಾದ, ಚೆನ್ನಾಗಿ ಬೆಳಕಿರುವ ಫೋಟೋ ತೆಗೆಯಿರಿ\n` +
    `2. ಆ ಫೋಟೋವನ್ನು ಈ ಚಾಟ್‌ಗೆ ಕಳುಹಿಸಿ\n` +
    `3. ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಕೆಲವು ಸೆಕೆಂಡ್ ಕಾಯಿರಿ\n\n` +
    `*ಉತ್ತಮ ಫಲಿತಾಂಶಕ್ಕೆ ಸಲಹೆಗಳು:*\n` +
    `  • ಹೆಸರು ಮತ್ತು ಘಟಕಾಂಶಗಳ ಮೇಲೆ ಗಮನವಿಡಿ\n` +
    `  • ಪ್ರಜ್ವಲ ಮತ್ತು ನೆರಳು ಬೇಡ\n` +
    `  • ಸ್ಥಿರವಾಗಿ ಹತ್ತಿರದಿಂದ ಹಿಡಿಯಿರಿ\n\n` +
    `*ಆದೇಶಗಳು:*\n` +
    `  /start — ಸ್ವಾಗತ ಸಂದೇಶ\n` +
    `  /language — ಭಾಷೆ ಬದಲಾಯಿಸಿ\n` +
    `  /help — ಈ ಸಹಾಯ ತೋರಿಸಿ\n` +
    `  /usage — ಇಂದಿನ ಉಳಿದ ಸ್ಕ್ಯಾನ್‌ಗಳು\n\n` +
    KN_DISCLAIMER,
  usage: (used, limit, remaining) =>
    `📊 *ಇಂದಿನ ಬಳಕೆ:* ${limit} ರಲ್ಲಿ ${used} ಸ್ಕ್ಯಾನ್ ಬಳಸಲಾಗಿದೆ\n` +
    `ಉಳಿದಿರುವುದು: *${remaining}*\n\n` +
    KN_DISCLAIMER,
  rateLimit: (hours, limit) =>
    `🛑 *ದಿನದ ಮಿತಿ ತಲುಪಿದೆ*\n\n` +
    `ಇಂದಿಗೆ ನಿಮ್ಮ ${limit} ಉಚಿತ ಸ್ಕ್ಯಾನ್‌ಗಳನ್ನು ಬಳಸಿದ್ದೀರಿ. ` +
    `ಸುಮಾರು ${hours} ಗಂಟೆಯಲ್ಲಿ ನಿಮ್ಮ ಮಿತಿ ಮರುಹೊಂದಿಸಲ್ಪಡುತ್ತದೆ.\n\n` +
    KN_DISCLAIMER,
  lowConfidence: (reason) =>
    `🔍 *ಇದನ್ನು ಖಚಿತವಾಗಿ ಓದಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ*\n\n` +
    (reason ? `_${escapeMd(reason)}_\n\n` : '') +
    `ನಿಮ್ಮ ಸುರಕ್ಷತೆಗಾಗಿ ನಾನು ಔಷಧಿಯ ಹೆಸರನ್ನು ಊಹಿಸುವುದಿಲ್ಲ — ತಪ್ಪು ಊಹೆ ಅಪಾಯಕಾರಿಯಾಗಬಹುದು.\n\n` +
    `ದಯವಿಟ್ಟು ಹೆಚ್ಚು ಸ್ಪಷ್ಟ ಫೋಟೋ ಕಳುಹಿಸಿ:\n` +
    `  • ಒಳ್ಳೆಯ ಬೆಳಕು, ಪ್ರಜ್ವಲ ಇಲ್ಲದೆ\n` +
    `  • ಔಷಧಿಯ ಹೆಸರು ಮತ್ತು ಘಟಕಾಂಶಗಳ ಮೇಲೆ ಗಮನ\n` +
    `  • ಕ್ಯಾಮೆರಾವನ್ನು ಸ್ಥಿರವಾಗಿ ಹತ್ತಿರ ಹಿಡಿಯಿರಿ\n\n` +
    `_ಈ ಪ್ರಯತ್ನವನ್ನು ನಿಮ್ಮ ದಿನದ ಮಿತಿಯಲ್ಲಿ ಎಣಿಸಲಾಗಿಲ್ಲ._\n\n` +
    KN_DISCLAIMER,
  notAMedicine:
    `🤔 *ಇದು ಔಷಧಿ ಪ್ಯಾಕೆಟ್‌ನಂತೆ ಕಾಣುತ್ತಿಲ್ಲ*\n\n` +
    `ದಯವಿಟ್ಟು ಔಷಧಿಯ ಸ್ಟ್ರಿಪ್, ಬಾಟಲ್ ಅಥವಾ ಬಾಕ್ಸ್‌ನ ಸ್ಪಷ್ಟ ಫೋಟೋ ಕಳುಹಿಸಿ.\n\n` +
    `_ಈ ಪ್ರಯತ್ನವನ್ನು ನಿಮ್ಮ ದಿನದ ಮಿತಿಯಲ್ಲಿ ಎಣಿಸಲಾಗಿಲ್ಲ._\n\n` +
    KN_DISCLAIMER,
  sendPhoto:
    `ದಯವಿಟ್ಟು ನಿಮ್ಮ ಔಷಧಿ ಲೇಬಲ್‌ನ *ಫೋಟೋ* ಕಳುಹಿಸಿ.\n\n` +
    `ಸೂಚನೆಗಳಿಗೆ /help ಬಳಸಿ.\n\n` +
    KN_DISCLAIMER,
  sendImage: `ದಯವಿಟ್ಟು ನಿಮ್ಮ ಔಷಧಿ ಲೇಬಲ್‌ನ *ಚಿತ್ರ* ಕಳುಹಿಸಿ.\n\n` + KN_DISCLAIMER,
  downloadFailed:
    `❌ ಚಿತ್ರವನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಕಳುಹಿಸಿ.\n\n` + KN_DISCLAIMER,
  extractionFailed:
    `❌ ಚಿತ್ರವನ್ನು ಓದಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಹೆಚ್ಚು ಸ್ಪಷ್ಟ ಫೋಟೋ ಕಳುಹಿಸಿ.\n\n` + KN_DISCLAIMER,
  imageTooLarge: (mb) =>
    `📦 ಚಿತ್ರ ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ. ದಯವಿಟ್ಟು ${mb} MB ಗಿಂತ ಕಡಿಮೆ ಇರುವ ಚಿತ್ರ ಕಳುಹಿಸಿ.\n\n` +
    KN_DISCLAIMER,
  somethingWrong:
    `❌ ಮಾಹಿತಿ ಸಿದ್ಧಪಡಿಸುವಾಗ ಏನೋ ತಪ್ಪಾಯಿತು. ದಯವಿಟ್ಟು ಫೋಟೋವನ್ನು ಮತ್ತೆ ಕಳುಹಿಸಿ.\n\n` +
    KN_DISCLAIMER,
  purposeQuestion: (name, ingredients) =>
    `✅ ನಾನು ಓದಿದೆ: *${escapeMd(name)}*\n` +
    (ingredients ? `ಘಟಕಾಂಶ: ${escapeMd(ingredients)}\n\n` : '\n') +
    `*ಸರಿಯಾದ* ಮಾಹಿತಿ ನೀಡಲು, ನೀವು ಇದನ್ನು ಯಾವುದಕ್ಕೆ ಬಳಸುತ್ತಿದ್ದೀರಿ?`,
  purposeTypePrompt:
    `ನೀವು ಇದನ್ನು ಯಾವುದಕ್ಕೆ ಬಳಸುತ್ತಿದ್ದೀರಿ ಎಂದು ಟೈಪ್ ಮಾಡಿ (ಉದಾ. "ಚರ್ಮದ ಗುರುತುಗಳಿಗೆ", "ಮುಟ್ಟಿಗೆ").`,
  purposeLabels: {
    skin: '🧴 ಚರ್ಮ / ಕಲೆಗಳು',
    bleeding: '🩸 ರಕ್ತಸ್ರಾವ / ಮುಟ್ಟು',
    pain: '💢 ನೋವು / ಜ್ವರ',
    infection: '🦠 ಸೋಂಕು',
    bp: '❤️ ಬಿಪಿ / ಹೃದಯ',
    sugar: '🩺 ಸಕ್ಕರೆ ಕಾಯಿಲೆ',
    acidity: '🔥 ಆಮ್ಲೀಯತೆ / ಹೊಟ್ಟೆ',
    allergy: '🤧 ಅಲರ್ಜಿ / ಶೀತ',
  },
  typeLabel: '✍️ ನನ್ನ ಕಾರಣ ಬರೆಯಿರಿ',
  skipLabel: '⏭️ ಬಿಟ್ಟುಬಿಡಿ',
  analysis: {
    contains: 'ಒಳಗೊಂಡಿದೆ',
    drugClass: 'ಔಷಧಿಯ ಪ್ರಕಾರ',
    howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    commonUses: 'ಸಾಮಾನ್ಯವಾಗಿ ಬಳಸುವುದು',
    commonSideEffects: 'ಸಾಮಾನ್ಯ ಅಡ್ಡ ಪರಿಣಾಮಗಳು',
    seriousSideEffects: '🚑 ಈ ಲಕ್ಷಣಗಳಿದ್ದರೆ ತಕ್ಷಣ ವೈದ್ಯರನ್ನು ಭೇಟಿಯಾಗಿ',
    warnings: '⚠️ ಎಚ್ಚರಿಕೆಗಳು',
    warningKeys: {
      pregnancy: 'ಗರ್ಭಾವಸ್ಥೆ',
      liver: 'ಯಕೃತ್ತು',
      kidney: 'ಮೂತ್ರಪಿಂಡ',
      alcohol: 'ಮದ್ಯ',
      children: 'ಮಕ್ಕಳು',
      elderly: 'ವೃದ್ಧರು',
    },
    interactions: 'ಇವುಗಳ ಬಗ್ಗೆ ಎಚ್ಚರ ವಹಿಸಿ',
    overdoseAwareness: '🚨 ಮಿತಿಮೀರಿದ ಸೇವನೆಯ ಅರಿವು',
    fdaVerified: '✓ ಘಟಕಾಂಶವನ್ನು FDA ಔಷಧಿ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.',
  },
};

/* --------------------------------- Registry -------------------------------- */

const STRINGS: Record<LangCode, Strings> = { en, kn };

/** Get the string table for a language (falls back to the default language). */
export function t(lang: LangCode): Strings {
  return STRINGS[lang] ?? STRINGS[DEFAULT_LANG];
}
