import type { MedicineAnalysis } from '@/types';
import { t } from '@/config/i18n';
import { DEFAULT_LANG, type LangCode } from '@/config/languages';

/**
 * Render a MedicineAnalysis into a clean, elder-friendly Telegram message.
 *
 * Section LABELS come from the i18n table (static, free). The VALUES inside
 * (uses, side effects, warnings, ...) were generated by the LLM directly in the
 * user's language. Medicine and ingredient names stay as printed.
 */
export function formatAnalysisForTelegram(
  a: MedicineAnalysis,
  lang: LangCode = DEFAULT_LANG
): string {
  const L = t(lang);
  const A = L.analysis;
  const s: string[] = [];

  s.push(`💊 *${escapeMarkdown(a.medicineName)}*`);

  if (a.activeIngredients.length > 0) {
    s.push(`*${A.contains}:* ${a.activeIngredients.map(escapeMarkdown).join(', ')}`);
  }

  if (a.drugClass) {
    s.push(`*${A.drugClass}:* ${escapeMarkdown(a.drugClass)}`);
  }

  if (a.howItWorks) {
    s.push(`*${A.howItWorks}:* ${escapeMarkdown(a.howItWorks)}`);
  }

  if (a.commonUses.length > 0) {
    s.push(`*${A.commonUses}:*\n${bullets(a.commonUses)}`);
  }

  if (a.commonSideEffects.length > 0) {
    s.push(`*${A.commonSideEffects}:*\n${bullets(a.commonSideEffects)}`);
  }

  if (a.seriousSideEffects.length > 0) {
    s.push(`*${A.seriousSideEffects}:*\n${bullets(a.seriousSideEffects)}`);
  }

  const activeWarnings = Object.entries(a.warnings).filter(
    ([, msg]) => msg !== null && msg.trim().length > 0
  ) as [keyof typeof A.warningKeys, string][];
  if (activeWarnings.length > 0) {
    const list = activeWarnings
      .map(([k, msg]) => `  • *${A.warningKeys[k] ?? capitalize(k)}:* ${escapeMarkdown(msg)}`)
      .join('\n');
    s.push(`*${A.warnings}:*\n${list}`);
  }

  if (a.interactions.length > 0) {
    s.push(`*${A.interactions}:*\n${bullets(a.interactions)}`);
  }

  if (a.overdoseAwareness) {
    s.push(`*${A.overdoseAwareness}:* ${escapeMarkdown(a.overdoseAwareness)}`);
  }

  if (a.fdaVerified) {
    s.push(`_${A.fdaVerified}_`);
  }

  s.push(`\n${L.disclaimer}`);

  return s.join('\n\n');
}

function bullets(items: string[]): string {
  return items.map((i) => `  • ${escapeMarkdown(i)}`).join('\n');
}

function escapeMarkdown(text: string): string {
  return text.replace(/([*_`\[\]])/g, '\\$1');
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function formatRateLimitMessage(
  resetAt: Date,
  limit: number,
  lang: LangCode = DEFAULT_LANG
): string {
  const hours = Math.ceil((resetAt.getTime() - Date.now()) / (1000 * 60 * 60));
  return t(lang).rateLimit(hours, limit);
}

/**
 * Shown when the medicine name/ingredients couldn't be read confidently.
 * IMPORTANT: tells the user their scan was NOT counted, so they retry freely.
 */
export function formatLowConfidenceMessage(
  reason: string | null,
  lang: LangCode = DEFAULT_LANG
): string {
  return t(lang).lowConfidence(reason);
}

export function formatNotAMedicineMessage(lang: LangCode = DEFAULT_LANG): string {
  return t(lang).notAMedicine;
}

export function formatWelcomeMessage(lang: LangCode = DEFAULT_LANG): string {
  return t(lang).welcome;
}

export function formatHelpMessage(lang: LangCode = DEFAULT_LANG): string {
  return t(lang).help;
}
